"""
gyroid_slicer.py

Purpose: mathematically slice a triangle mesh into layers and produce a gyroid
infill as analytic implicit-level-contours. Supports nozzle width, layer
height, wall count (including top and bottom layers).

Design notes:
 - Uses exact triangle-plane intersection to build 2D polygons for each layer.
 - Defines gyroid as an analytic implicit function G(x,y,z)-t = 0 and traces
   contours in the layer plane by predictor-corrector continuation.
 - Walls (perimeter) are generated by polygon offset using pyclipper if
   available. If pyclipper is not installed, the code will raise a helpful
   error telling you to pip install pyclipper (that's the best option).
 - Top/bottom layers are handled by producing a simple parallel-line fill
   (mathematically clipped to layer polygon) to ensure a solid surface.

Dependencies (recommended): numpy, pyclipper, shapely (optional but useful
for plotting / geometry checks). All are pip-installable.

This is a practical, readable implementation rather than the absolutely
most-optimized production slicer. It focuses on numerical robustness and
clarity.

Example usage at bottom.
"""

from __future__ import annotations
import math
import sys
from dataclasses import dataclass
from typing import List, Tuple, Optional, Sequence

import numpy as np

# Optional helper libraries
try:
    import pyclipper
except Exception:
    pyclipper = None

try:
    from shapely.geometry import Polygon, LineString, Point
    from shapely.ops import unary_union
except Exception:
    Polygon = None
    LineString = None
    Point = None
    unary_union = None


# ----------------------------- Basic Geometry -----------------------------

Vec3 = Tuple[float, float, float]
Vec2 = Tuple[float, float]


@dataclass
class Triangle:
    v0: Vec3
    v1: Vec3
    v2: Vec3


def intersect_triangle_plane(tri: Triangle, z0: float) -> List[Vec2]:
    """Return 0,1,2 or 3 intersection points (2 for proper intersection) in XY plane.
    Points returned as (x,y).
    """
    verts = [tri.v0, tri.v1, tri.v2]
    pts: List[Vec2] = []
    for i in range(3):
        a = verts[i]
        b = verts[(i + 1) % 3]
        za = a[2]
        zb = b[2]
        if (za - z0) == 0.0:
            # Vertex lies on plane — return that point
            pts.append((a[0], a[1]))
        if (za - z0) * (zb - z0) < 0.0:
            t = (z0 - za) / (zb - za)
            x = a[0] + t * (b[0] - a[0])
            y = a[1] + t * (b[1] - a[1])
            pts.append((x, y))
    # Remove duplicates (within epsilon)
    uniq: List[Vec2] = []
    eps = 1e-9
    for p in pts:
        if not any((abs(p[0] - q[0]) < eps and abs(p[1] - q[1]) < eps) for q in uniq):
            uniq.append(p)
    return uniq


def build_layer_polygons(triangles: Sequence[Triangle], z0: float) -> List[List[Vec2]]:
    """Slice a mesh at z=z0; return list of polygons (list of ordered vertices).

    Strategy: collect intersection segments from triangles (two pts -> segment),
    then stitch them by endpoints using hashing to form closed loops.
    """
    # collect segments
    segs: List[Tuple[Vec2, Vec2]] = []
    for tri in triangles:
        pts = intersect_triangle_plane(tri, z0)
        if len(pts) == 2:
            segs.append((pts[0], pts[1]))
        elif len(pts) == 3:
            # triangle coplanar - produce three edges
            segs.append((pts[0], pts[1]))
            segs.append((pts[1], pts[2]))
            segs.append((pts[2], pts[0]))
    if not segs:
        return []

    # endpoint hashing
    def key(p: Vec2) -> Tuple[int, int]:
        scale = 1e9
        return (int(round(p[0] * scale)), int(round(p[1] * scale)))

    endpoints = {}
    for a, b in segs:
        endpoints.setdefault(key(a), []).append((a, b))
        endpoints.setdefault(key(b), []).append((b, a))

    loops: List[List[Vec2]] = []
    used = set()

    for a, b in segs:
        if (a, b) in used:
            continue
        poly = [a, b]
        used.add((a, b))
        current = b
        while True:
            k = key(current)
            candidates = endpoints.get(k, [])
            next_seg = None
            for seg in candidates:
                if seg not in used:
                    next_seg = seg
                    break
            if next_seg is None:
                break
            used.add(next_seg)
            nxt_point = next_seg[1]
            if abs(nxt_point[0] - poly[0][0]) < 1e-9 and abs(nxt_point[1] - poly[0][1]) < 1e-9:
                # closed
                break
            poly.append(nxt_point)
            current = nxt_point
        # If poly is closed (last equals first) remove duplicate
        if len(poly) >= 3:
            # sometimes ordering may be reversed or not consistent; trust this as polygon
            loops.append(poly)
    # Optionally: sort loops by area (outer first) — user can decide
    loops_sorted = sorted(loops, key=lambda P: abs(polygon_area(P)), reverse=True)
    return loops_sorted


def polygon_area(poly: List[Vec2]) -> float:
    s = 0.0
    n = len(poly)
    for i in range(n):
        x1, y1 = poly[i]
        x2, y2 = poly[(i + 1) % n]
        s += x1 * y2 - x2 * y1
    return 0.5 * s


# ----------------------------- Gyroid Field --------------------------------

class GyroidField:
    def __init__(self, period: float = 10.0, isovalue: float = 0.0, phase=(0.0, 0.0, 0.0)):
        self.period = float(period)
        self.a = 2.0 * math.pi / self.period
        self.t = float(isovalue)
        self.phi_x, self.phi_y, self.phi_z = phase

    def G(self, x: float, y: float, z: float) -> float:
        a = self.a
        px = a * x + self.phi_x
        py = a * y + self.phi_y
        pz = a * z + self.phi_z
        return math.sin(px) * math.cos(py) + math.sin(py) * math.cos(pz) + math.sin(pz) * math.cos(px)

    def F(self, x: float, y: float, z: float) -> float:
        return self.G(x, y, z) - self.t

    def gradient(self, x: float, y: float, z: float) -> Tuple[float, float, float]:
        a = self.a
        px = a * x + self.phi_x
        py = a * y + self.phi_y
        pz = a * z + self.phi_z
        # d/dx of G: a * (cos(px)cos(py) - sin(pz)sin(px))
        gx = a * (math.cos(px) * math.cos(py) - math.sin(pz) * math.sin(px))
        gy = a * (math.cos(py) * math.cos(pz) - math.sin(px) * math.sin(py))
        gz = a * (math.cos(pz) * math.cos(px) - math.sin(py) * math.sin(pz))
        return gx, gy, gz


# ----------------------------- Contour Tracing ------------------------------

def trace_contour_2d(seed: Vec2, f_xy, grad_xy, step=0.5, max_steps=10000, tol=1e-6) -> List[Vec2]:
    """Trace a single closed implicit contour f(x,y)=0 starting from seed.

    f_xy(x,y) -> float
    grad_xy(x,y) -> (fx,fy)

    Implements simple predictor-corrector: take small tangent step then
    project back by Newton along normal.
    """
    path: List[Vec2] = []
    x, y = seed
    path.append((x, y))
    for i in range(max_steps):
        fx, fy = grad_xy(x, y)
        norm = math.hypot(fx, fy)
        if norm == 0:
            # stuck; break
            break
        # tangent vector
        tx, ty = -fy / norm, fx / norm
        # predictor
        px, py = x + tx * step, y + ty * step
        # correct: Newton along normal direction
        for _ in range(8):
            val = f_xy(px, py)
            gx, gy = grad_xy(px, py)
            nrm = math.hypot(gx, gy)
            if nrm == 0:
                break
            nx, ny = gx / nrm, gy / nrm
            # 1D Newton step along normal
            denom = gx * nx + gy * ny
            if abs(denom) < 1e-12:
                break
            alpha = -val / (gx * nx + gy * ny)
            px += alpha * nx
            py += alpha * ny
            if abs(val) < tol:
                break
        x_new, y_new = px, py
        path.append((x_new, y_new))
        x, y = x_new, y_new
        # closure test: distance to seed small after some steps
        if i > 10 and math.hypot(x - seed[0], y - seed[1]) < step * 0.5:
            break
    return path


def find_edge_seeds(polygon: List[Vec2], f_xy) -> List[Vec2]:
    """Find sign changes on polygon edges and return seed points for contours."""
    seeds: List[Vec2] = []
    for i in range(len(polygon)):
        a = polygon[i]
        b = polygon[(i + 1) % len(polygon)]
        fa = f_xy(a[0], a[1])
        fb = f_xy(b[0], b[1])
        if fa == 0.0:
            seeds.append(a)
        if fa * fb < 0.0:
            # bracketed; bisection to find point
            t0, t1 = 0.0, 1.0
            for _ in range(40):
                tm = 0.5 * (t0 + t1)
                xm = a[0] + (b[0] - a[0]) * tm
                ym = a[1] + (b[1] - a[1]) * tm
                fm = f_xy(xm, ym)
                if fa * fm <= 0.0:
                    t1 = tm
                    fb = fm
                else:
                    t0 = tm
                    fa = fm
            xm = a[0] + (b[0] - a[0]) * 0.5 * (t0 + t1)
            ym = a[1] + (b[1] - a[1]) * 0.5 * (t0 + t1)
            seeds.append((xm, ym))
    return seeds


# ----------------------------- Polygon Offsets --------------------------------

def offset_polygon(poly: List[Vec2], delta: float) -> List[List[Vec2]]:
    """Offset polygon (positive outward, negative inward) using pyclipper.

    Returns list of offset polygons (one or more) as lists of (x,y) floats.
    Requires pyclipper.
    """
    if pyclipper is None:
        raise RuntimeError("pyclipper is required for polygon offsets. pip install pyclipper")
    scale = 1e6
    subj = [(int(round(p[0] * scale)), int(round(p[1] * scale))) for p in poly]
    pc = pyclipper.PyclipperOffset()
    pc.AddPath(subj, pyclipper.JT_ROUND, pyclipper.ET_CLOSEDPOLYGON)
    solution = pc.Execute(delta * scale)
    # Convert back
    out = []
    for sol in solution:
        out.append([(pt[0] / scale, pt[1] / scale) for pt in sol])
    return out


# ----------------------------- Top/Bottom Fill --------------------------------

def parallel_line_fill(poly: List[Vec2], spacing: float) -> List[List[Vec2]]:
    """Simple mathematical parallel-line fill (lines along X axis) clipped to polygon.

    This produces a set of line segments (each a list of two points) covering the
    polygon in an ordered fashion. It is deterministic and avoids raster block
    carving — it's an analytic intersection of straight lines with polygon edges.
    """
    # bounding box
    xs = [p[0] for p in poly]
    ys = [p[1] for p in poly]
    minx, maxx = min(xs), max(xs)
    miny, maxy = min(ys), max(ys)
    lines: List[List[Vec2]] = []
    y = miny + spacing * 0.5
    while y < maxy:
        # intersect horizontal line y with polygon edges
        inters: List[float] = []
        for i in range(len(poly)):
            a = poly[i]
            b = poly[(i + 1) % len(poly)]
            if (a[1] <= y and b[1] > y) or (b[1] <= y and a[1] > y):
                t = (y - a[1]) / (b[1] - a[1])
                x = a[0] + t * (b[0] - a[0])
                inters.append(x)
        inters.sort()
        # pairwise create segments
        for i in range(0, len(inters), 2):
            if i + 1 < len(inters):
                lines.append([(inters[i], y), (inters[i + 1], y)])
        y += spacing
    return lines


# ----------------------------- High level slicer --------------------------------

@dataclass
class SliceResult:
    z: float
    perimeters: List[List[Vec2]]
    infill_paths: List[List[Vec2]]


def slice_mesh_with_gyroid(triangles: Sequence[Triangle],
                           layer_height: float,
                           nozzle_width: float,
                           wall_count: int,
                           top_layers: int,
                           bottom_layers: int,
                           gyroid_period: float,
                           gyroid_isovalue: float = 0.0) -> List[SliceResult]:
    # mesh z range
    zs = [v[2] for tri in triangles for v in (tri.v0, tri.v1, tri.v2)]
    minz, maxz = min(zs), max(zs)
    # compute number of layers
    n_layers = int(math.ceil((maxz - minz) / layer_height))
    gf = GyroidField(period=gyroid_period, isovalue=gyroid_isovalue)

    results: List[SliceResult] = []
    for layer_idx in range(n_layers):
        z0 = minz + (layer_idx + 0.5) * layer_height
        polys = build_layer_polygons(triangles, z0)
        perimeters: List[List[Vec2]] = []
        infill_paths: List[List[Vec2]] = []
        for poly in polys:
            # generate walls by inward offsets
            offsets = [poly]
            try:
                for w in range(wall_count):
                    inset = offset_polygon(offsets[-1], -nozzle_width)
                    if not inset:
                        break
                    offsets.append(inset[0])
                perimeters.extend(offsets)
            except RuntimeError:
                # fallback: just use outer poly as single perimeter
                perimeters.append(poly)
            # decide if this is top or bottom layer
            if layer_idx < bottom_layers or layer_idx >= n_layers - top_layers:
                # top/bottom: do line fill
                lines = parallel_line_fill(offsets[-1], nozzle_width * 0.9)
                # append each line as a path
                for ln in lines:
                    infill_paths.append(ln)
                continue
            # regular gyroid infill inside the innermost offset
            inner = offsets[-1]
            if not inner:
                continue
            # build f_xy,grad for this z layer
            def f_xy(x, y, _z=z0, gf_local=gf):
                return gf_local.F(x, y, _z)

            def grad_xy(x, y, _z=z0, gf_local=gf):
                gx, gy, gz = gf_local.gradient(x, y, _z)
                return gx, gy

            # find seeds on polygon edges
            seeds = find_edge_seeds(inner, f_xy)
            traced = []
            for s in seeds:
                path = trace_contour_2d(s, f_xy, grad_xy, step=nozzle_width * 0.5, max_steps=5000)
                if len(path) > 10:
                    infill_paths.append(path)
        results.append(SliceResult(z=z0, perimeters=perimeters, infill_paths=infill_paths))
    return results


# ----------------------------- Example / CLI --------------------------------

if __name__ == '__main__':
    def demo_box_mesh(x0, y0, z0, x1, y1, z1):
        # simple axis-aligned box mesh (12 triangles)
        verts = [
            (x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
            (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1),
        ]
        tris_idx = [
            (0, 1, 2), (0, 2, 3),
            (4, 6, 5), (4, 7, 6),
            (0, 4, 5), (0, 5, 1),
            (1, 5, 6), (1, 6, 2),
            (2, 6, 7), (2, 7, 3),
            (3, 7, 4), (3, 4, 0)
        ]
        return [Triangle(verts[a], verts[b], verts[c]) for (a, b, c) in tris_idx]

    # demo parameters
    mesh = demo_box_mesh(0, 0, 0, 30, 30, 10)
    res = slice_mesh_with_gyroid(mesh,
                                 layer_height=0.4,
                                 nozzle_width=0.8,
                                 wall_count=2,
                                 top_layers=3,
                                 bottom_layers=3,
                                 gyroid_period=8.0)
    print(f"generated {len(res)} layers")
    # print summary
    for r in res[:3]:
        print(f"z={r.z:.3f}, perimeters={len(r.perimeters)}, infill paths={len(r.infill_paths)}")

    print("Demo done. Use functions programmatically for full control.")
